### ISSUE TITLE
License for the code?

### ISSUE THREAD

**Issue by CRImier** [RutledgePaulV/sudoku-generator#1]
Hi! What's the license for your code? I'd like to make a [ZPUI](https://zpui.readthedocs.io/en/latest/) app around your generator code and ship it with ZPUI by default (with attribution in the UI and source tree) - however, I can't reuse your code because there's no license. Would you be OK with something like Apache or MIT? Here's [a tutorial on adding licenses](https://help.github.com/articles/adding-a-license-to-a-repository/) in GitHub repos easily - alternatively, I can make a pull request with license of your choosing so that you can accept it with a single button press. Let me know what you'd be OK with.

Cheers,
Arsenijs.

**Comment by RutledgePaulV** [comment]
Hi Arsenijs,

Yes, I'm okay with MIT and wish you luck with your project.

License added!

**Comment by CRImier** [comment]
Thank you very much!
